repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: Rustfmt
        entry: cargo fmt -- --check
        language: system
        types: [rust]

      - id: clippy
        name: Clippy
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: tests
        name: Cargo Tests
        entry: cargo test --locked
        language: system
        types: [rust]
        pass_filenames: false

